version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  montecarlo_worker:
    image: worker:latest
    environment:
      - REDIS_HOST=redis
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - redis
      - collector
    restart: always
  
  collector:
    image: collector:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

volumes:
  redis_data:
