version: "3.8"

services:
  api:
    image: montecarlo_app  # zamiast build
    ports:
      - "8000:8000"
    networks:
      - swarm-net

  worker:
    image: montecarlo_app  # zamiast build
    command: uvicorn worker:app --host 0.0.0.0 --port 8000
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - swarm-net

networks:
  swarm-net:
    driver: overlay